### ISSUE TITLE
Support for ActiveAdmin 2.0

### ISSUE THREAD

**Issue by julitrows** [ypylypenko/activeadmin_simplemde#3]
Hi, first of all: thanks for this component and the work you put into it :)

So, ActiveAdmin [2.0](https://github.com/activeadmin/activeadmin/releases/tag/v2.0.0) is out (and [soon 2.1](https://github.com/activeadmin/activeadmin/issues/5765)), but this gem is stuck requiring `~> 1.0`

Any plans for releasing a v2.x compatible version?

Thanks again!

EDIT: #2 already takes care of this. Any temptative merging date?

**Comment by ypylypenko** [comment]
Hi @julitrows. Thank you for your feedback. I plan to make changes in the next few days

**Comment by ypylypenko** [comment]
Sorry to keep you waiting. Just released a new version.
